In [2]:
import numpy as np

data = np.load("C:/Users/zahin/Downloads/N-Caltech101/N-Caltech101/training/dollar_bill/dollar_bill_4.npy")
print(data)

[[ 6.00000e+00  8.60000e+01  6.70000e-05 -1.00000e+00]
 [ 4.70000e+01  8.20000e+01  9.90000e-05  1.00000e+00]
 [ 2.80000e+01  4.80000e+01  1.63000e-04  1.00000e+00]
 ...
 [ 1.68000e+02  5.60000e+01  2.96196e-01 -1.00000e+00]
 [ 1.37000e+02  8.50000e+01  2.96204e-01 -1.00000e+00]
 [ 6.30000e+01  2.10000e+01  2.96206e-01 -1.00000e+00]]
